adb devices
#adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.corner
#adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.double
#adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural_wide_back
#adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.tall
#adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.threebutton
#adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.twobutton
#adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back
#adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural
#adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural_narrow_back
#adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.waterfall
#adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.hole
#adb shell pm uninstall -k --user 0 com.android.theme.icon.square
#adb shell pm uninstall -k --user 0 com.android.theme.color.cinnamon
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.systemui
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.android
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.themepicker
#adb shell pm uninstall -k --user 0 com.android.theme.color.black
#adb shell pm uninstall -k --user 0 com.android.theme.color.green
#adb shell pm uninstall -k --user 0 com.android.theme.color.ocean
#adb shell pm uninstall -k --user 0 com.android.theme.color.space
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.launcher
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.settings
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.settings
#adb shell pm uninstall -k --user 0 com.android.theme.icon.teardrop
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.systemui
#adb shell pm uninstall -k --user 0 com.android.theme.font.notoserifsource
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.android
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.systemui
#adb shell pm uninstall -k --user 0 com.android.theme.icon.squircle
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.launcher
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.launcher
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.themepicker
#adb shell pm uninstall -k --user 0 com.android.theme.color.orchid
#adb shell pm uninstall -k --user 0 com.android.theme.color.purple
#adb shell pm uninstall -k --user 0 com.android.theme.icon.roundedrect
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.settings
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.android
#adb shell pm uninstall -k --user 0 com.android.theme.icon.pebble
#adb shell pm uninstall -k --user 0 com.android.theme.icon.vessel
#adb shell pm uninstall -k --user 0 com.android.theme.icon.taperedrect
#adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.themepicker
adb shell pm uninstall -k --user 0 com.vivo.game
adb shell pm uninstall -k --user 0 com.vivo.gamewatch
adb shell pm uninstall -k --user 0 com.vivo.globalsearch
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.coffeetime
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.coralsea
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.galaxy
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.geometry
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.silk
#adb shell pm uninstall -k --user 0 com.vivo.weather
#adb shell pm uninstall -k --user 0 com.vivo.weather.provider
#adb shell pm uninstall -k --user 0 com.vivo.widget.calendar
adb shell pm uninstall -k --user 0 com.vlife.vivo.wallpaper
adb shell pm uninstall -k --user 0 com.yozo.vivo.office
adb shell pm uninstall -k --user 0 ctrip.android.view
adb shell pm uninstall -k --user 0 com.iqoo.secure
adb shell pm uninstall -k --user 0 com.sankuai.meituan
adb shell pm uninstall -k --user 0 com.sohu.inputmethod.sogou.vivo
adb shell pm uninstall -k --user 0 com.vivo.SmartKey
adb shell pm uninstall -k --user 0 com.vivo.smartmultiwindow
adb shell pm uninstall -k --user 0 com.vivo.smartshot
adb shell pm uninstall -k --user 0 com.vivo.space
adb shell pm uninstall -k --user 0 com.vivo.Tips
adb shell pm uninstall -k --user 0 com.vivo.videoeditor
adb shell pm uninstall -k --user 0 com.vivo.video.floating
adb shell pm uninstall -k --user 0 com.vivo.vivokaraoke
adb shell pm uninstall -k --user 0 com.vivo.voicewakeup
adb shell pm uninstall -k --user 0 com.bbk.appstore
#adb shell pm uninstall -k --user 0 com.bbk.calendar
adb shell pm uninstall -k --user 0 com.bbk.cloud
adb shell pm uninstall -k --user 0 com.bbk.iqoo.feedback
adb shell pm uninstall -k --user 0 com.bbk.iqoo.logsystem
#adb shell pm uninstall -k --user 0 com.bbk.launcher2
adb shell pm uninstall -k --user 0 com.bbk.photoframewidget
adb shell pm uninstall -k --user 0 com.bbk.scene.databaseprovider
adb shell pm uninstall -k --user 0 com.bbk.scene.launcher.theme
adb shell pm uninstall -k --user 0 com.android.bbklog
adb shell pm uninstall -k --user 0 com.android.bbkmusic
adb shell pm uninstall -k --user 0 com.android.VideoPlayer
adb shell pm uninstall -k --user 0 com.baidu.map.location
#adb shell pm uninstall -k --user 0 com.vivo.doubletimezoneclock
adb shell pm uninstall -k --user 0 com.vivo.dream.clock
adb shell pm uninstall -k --user 0 com.vivo.dream.music
adb shell pm uninstall -k --user 0 com.vivo.dream.weather
adb shell pm uninstall -k --user 0 com.vivo.easyshare
adb shell pm uninstall -k --user 0 com.vivo.email
adb shell pm uninstall -k --user 0 com.android.bbkcalculator
#adb shell pm uninstall -k --user 0 com.android.BBKClock
adb shell pm uninstall -k --user 0 com.android.BBKCrontab
#adb shell pm uninstall -k --user 0 com.bbk.theme
#adb shell pm uninstall -k --user 0 com.bbk.theme.resources
#adb shell pm uninstall -k --user 0 com.bbk.updater
adb shell pm uninstall -k --user 0 com.chaozh.iReader
adb shell pm uninstall -k --user 0 com.vivo.browser
adb shell pm uninstall -k --user 0 com.tencent.soter.soterserver
adb shell pm uninstall -k --user 0 com.iflytek.speechsuite
adb shell pm uninstall -k --user 0 com.vivo.aiengine
adb shell pm uninstall -k --user 0 com.vivo.aiservice
adb shell pm uninstall -k --user 0 com.vivo.aitranslate
adb shell pm uninstall -k --user 0 com.vivo.appfilter
adb shell pm uninstall -k --user 0 com.vivo.assistant
#adb shell pm uninstall -k --user 0 com.vivo.setupwizard
adb shell pm uninstall -k --user 0 com.vivo.carmode
adb shell pm uninstall -k --user 0 com.vivo.collage
#adb shell pm uninstall -k --user 0 com.vivo.compass
adb shell pm uninstall -k --user 0 com.vivo.contentcatcher
adb shell pm uninstall -k --user 0 com.vivo.favorite
#Do not delete the following software packages, otherwise the basic functions of the claw machine will be paralyzed!
#adb shell pm uninstall -k --user 0 com.vivo.upslide
#adb shell pm uninstall -k --user 0 com.vivo.vtouch
#adb shell pm uninstall -k --user 0 com.vivo.gallery
adb shell pm uninstall -k --user 0 com.vivo.doubleinstance
adb shell pm uninstall -k --user 0 com.vivo.ewarranty
adb shell pm uninstall -k --user 0 com.vivo.findphone
#adb shell pm uninstall -k --user 0 com.vivo.fingerprint
#adb shell pm uninstall -k --user 0 com.vivo.fingerprintui
#The following software package functions are in doubt, you can test it, article comments and feedback
adb shell pm uninstall -k --user 0 com.android.bbk.lockscreen3
adb shell pm uninstall -k --user 0 com.bbk.account
#adb shell pm uninstall -k --user 0 com.bbk.SuperPowerSave
adb shell pm uninstall -k --user 0 com.ibimuyu.lockscreen
adb shell pm uninstall -k --user 0 com.iqoo.engineermode
#adb shell pm uninstall -k --user 0 com.iqoo.powersaving
adb shell pm uninstall -k --user 0 com.vivo.abe
adb shell pm uninstall -k --user 0 com.vivo.agent
adb shell pm uninstall -k --user 0 com.vivo.audiofx
adb shell pm uninstall -k --user 0 com.vivo.bsptest
adb shell pm uninstall -k --user 0 com.vivo.daemonService
adb shell pm uninstall -k --user 0 com.vivo.devicereg
adb shell pm uninstall -k --user 0 com.vivo.flash
adb shell pm uninstall -k --user 0 com.vivo.floatingball
adb shell pm uninstall -k --user 0 com.vivo.fuelsummary
adb shell pm uninstall -k --user 0 com.vivo.hiboard
adb shell pm uninstall -k --user 0 com.vivo.hybrid
adb shell pm uninstall -k --user 0 com.vivo.magazine
adb shell pm uninstall -k --user 0 com.vivo.mediatune
adb shell pm uninstall -k --user 0 com.vivo.minscreen
adb shell pm uninstall -k --user 0 com.vivo.motionrecognition
adb shell pm uninstall -k --user 0 com.vivo.networkimprove
adb shell pm uninstall -k --user 0 com.vivo.networkstate
adb shell pm uninstall -k --user 0 com.vivo.nightpearl
adb shell pm uninstall -k --user 0 com.vivo.numbermark
adb shell pm uninstall -k --user 0 com.vivo.pem
#adb shell pm uninstall -k --user 0 com.vivo.permissionmanager
adb shell pm uninstall -k --user 0 com.vivo.pushservice
adb shell pm uninstall -k --user 0 com.vivo.quickpay
adb shell pm uninstall -k --user 0 com.vivo.safecenter
adb shell pm uninstall -k --user 0 com.vivo.scanner
adb shell pm uninstall -k --user 0 com.vivo.sdkplugin
adb shell pm uninstall -k --user 0 com.vivo.secime.service
adb shell pm uninstall -k --user 0 com.vivo.sim.contacts
adb shell pm uninstall -k --user 0 com.vivo.upnpserver
adb shell pm uninstall -k --user 0 com.vivo.wallet
adb shell pm uninstall -k --user 0 com.vivo.epm
adb shell pm uninstall -k --user 0 com.vivo.sos
adb shell pm uninstall -k --user 0 com.vivo.heduohao
adb shell pm uninstall -k --user 0 com.vivo.singularity
adb shell pm uninstall -k --user 0 com.android.vivo.tws.vivotws
adb shell pm uninstall -k --user 0 com.vivo.puresearch
adb shell pm uninstall -k --user 0 com.ringclip
adb shell pm uninstall -k --user 0 com.rongcard.eid
adb shell pm uninstall -k --user 0 com.dsi.ant.server
adb shell pm uninstall -k --user 0 com.vivo.omacp
adb shell pm uninstall -k --user 0 com.dsi.ant.server
adb shell pm uninstall -k --user 0 com.qualcomm.qti.qmmi
adb shell pm uninstall -k --user 0 com.android.providers.downloads.ui
adb shell pm uninstall -k --user 0 com.qualcomm.qti.uceShimService
adb shell pm uninstall -k --user 0 com.android.printspooler
adb shell pm uninstall -k --user 0 com.google.android.printservice.recommendation
adb shell pm uninstall -k --user 0 com.android.htmlviewer
adb shell pm uninstall -k --user 0 com.android.filemanager
adb shell pm uninstall -k --user 0 com.vivo.share
adb shell pm uninstall -k --user 0 com.vivo.dr
adb shell pm uninstall -k --user 0 com.vivo.childrenmode
adb shell pm uninstall -k --user 0 com.vivo.car.networking
adb shell pm uninstall -k --user 0 com.vivo.share
adb shell pm uninstall -k --user 0 com.vivo.smartanswer
adb shell pm uninstall -k --user 0 org.ifaa.aidl.manager
adb shell pm uninstall -k --user 0 com.google.ar.core
adb shell pm uninstall -k --user 0 com.baidu.input_vivo
adb shell pm uninstall -k --user 0 com.android.htmlviewer
adb shell pm uninstall -k --user 0 com.vivo.vms
adb shell pm uninstall -k --user 0 com.vivo.healthwidget
adb shell pm uninstall -k --user 0 com.vivo.widget.cleanspeed
adb shell pm uninstall -k --user 0 com.vivo.desktopstickers
adb shell pm uninstall -k --user 0 com.vivo.vhomeguide
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.behavior
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.behavioriqoo
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.monster
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.LightSpeed
adb shell pm uninstall -k --user 0 com.vivo.livewallpaper.Streamer
adb shell pm uninstall -k --user 0 com.vivo.gametrain
adb shell pm uninstall -k --user 0 com.vivo.deformer
adb shell pm uninstall -k --user 0 com.android.documentsui
#New method of uninstall apps, for apps with "Failure [DELETE_FAILED_USER_RESTRICTED]" code
#For Neo 855 based on originos 1.0 (android 11), replace 134 with 136
adb shell service call package 134 s16 com.vivo.wallet i32 0 i32 0
adb shell service call package 134 s16 com.vivo.agent i32 0 i32 0
adb shell service call package 134 s16 com.vivo.carlauncher i32 0 i32 0
adb shell service call package 134 s16 com.vivo.accessibility i32 0 i32 0
adb shell service call package 134 s16 com.vivo.card i32 0 i32 0
adb shell service call package 134 s16 com.vivo.remoteassistant i32 0 i32 0
adb shell service call package 134 s16 com.vivo.smartLife i32 0 i32 0
adb shell service call package 134 s16 com.vivo.familycare.local i32 0 i32 0 
adb shell service call package 134 s16 com.yuemeng.speechsuite i32 0 i32 0
adb shell service call package 134 s16 com.vivo.cipherchain i32 0 i32 0
PAUSE
