adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.corner
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.double
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural_wide_back
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.tall
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.threebutton
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.twobutton
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural_extra_wide_back
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural
adb shell pm uninstall -k --user 0 com.android.internal.systemui.navbar.gestural_narrow_back
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.waterfall
adb shell pm uninstall -k --user 0 com.android.internal.display.cutout.emulation.hole
adb shell pm uninstall -k --user 0 com.android.theme.icon.square
adb shell pm uninstall -k --user 0 com.android.theme.color.cinnamon
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.systemui
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.android
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.themepicker
adb shell pm uninstall -k --user 0 com.android.theme.color.black
adb shell pm uninstall -k --user 0 com.android.theme.color.green
adb shell pm uninstall -k --user 0 com.android.theme.color.ocean
adb shell pm uninstall -k --user 0 com.android.theme.color.space
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.launcher
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.settings
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.settings
adb shell pm uninstall -k --user 0 com.android.theme.icon.teardrop
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.systemui
adb shell pm uninstall -k --user 0 com.android.theme.font.notoserifsource
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.android
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.systemui
adb shell pm uninstall -k --user 0 com.android.theme.icon.squircle
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.launcher
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.launcher
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.filled.themepicker
adb shell pm uninstall -k --user 0 com.android.theme.color.orchid
adb shell pm uninstall -k --user 0 com.android.theme.color.purple
adb shell pm uninstall -k --user 0 com.android.theme.icon.roundedrect
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.settings
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.circular.android
adb shell pm uninstall -k --user 0 com.android.theme.icon.pebble
adb shell pm uninstall -k --user 0 com.android.theme.icon.vessel
adb shell pm uninstall -k --user 0 com.android.theme.icon.taperedrect
adb shell pm uninstall -k --user 0 com.android.theme.icon_pack.rounded.themepicker
