adb devices
adb shell pm uninstall --user 0 com.bbk.updater
adb shell pm uninstall --user 0 com.vivo.gamewatch
adb shell pm uninstall --user 0 com.vivo.globalsearch
#adb shell pm uninstall --user 0 com.vivo.widget.calendar
adb shell pm uninstall --user 0 com.vlife.vivo.wallpaper
adb shell pm uninstall --user 0 com.iqoo.secure
adb shell pm uninstall --user 0 com.sohu.inputmethod.sogou.vivo
adb shell pm uninstall --user 0 com.vivo.SmartKey
adb shell pm uninstall --user 0 com.vivo.smartmultiwindow
adb shell pm uninstall --user 0 com.vivo.smartshot
adb shell pm uninstall --user 0 com.vivo.space
adb shell pm uninstall --user 0 com.vivo.vivokaraoke
adb shell pm uninstall --user 0 com.vivo.voicewakeup
adb shell pm uninstall --user 0 com.bbk.appstore
#adb shell pm uninstall --user 0 com.bbk.calendar
adb shell pm uninstall --user 0 com.bbk.cloud
adb shell pm uninstall --user 0 com.bbk.iqoo.logsystem
#adb shell pm uninstall --user 0 com.bbk.launcher2
adb shell pm uninstall --user 0 com.bbk.photoframewidget
adb shell pm uninstall --user 0 com.bbk.scene.databaseprovider
adb shell pm uninstall --user 0 com.bbk.scene.launcher.theme
adb shell pm uninstall --user 0 com.android.bbklog
adb shell pm uninstall --user 0 com.android.bbkmusic
adb shell pm uninstall --user 0 com.android.VideoPlayer
adb shell pm uninstall --user 0 com.baidu.map.location
adb shell pm uninstall --user 0 com.vivo.easyshare
#adb shell pm uninstall --user 0 com.android.BBKClock
adb shell pm uninstall --user 0 com.android.BBKCrontab
#adb shell pm uninstall --user 0 com.bbk.theme
#adb shell pm uninstall --user 0 com.bbk.theme.resources
adb shell pm uninstall --user 0 com.vivo.browser
adb shell pm uninstall --user 0 com.tencent.soter.soterserver
adb shell pm uninstall --user 0 com.iflytek.speechsuite
adb shell pm uninstall --user 0 com.vivo.aiengine
adb shell pm uninstall --user 0 com.vivo.aiservice
adb shell pm uninstall --user 0 com.vivo.appfilter
adb shell pm uninstall --user 0 com.vivo.assistant
#adb shell pm uninstall --user 0 com.vivo.setupwizard
adb shell pm uninstall --user 0 com.vivo.contentcatcher
adb shell pm uninstall --user 0 com.vivo.favorite
#Do not delete the following software packages, otherwise the basic functions of the claw machine will be paralyzed!
#adb shell pm uninstall --user 0 com.vivo.upslide
#adb shell pm uninstall --user 0 com.vivo.vtouch
#adb shell pm uninstall --user 0 com.vivo.gallery
adb shell pm uninstall --user 0 com.vivo.doubleinstance
adb shell pm uninstall --user 0 com.vivo.ewarranty
adb shell pm uninstall --user 0 com.vivo.findphone
#adb shell pm uninstall --user 0 com.vivo.fingerprint
#adb shell pm uninstall --user 0 com.vivo.fingerprintui
adb shell pm uninstall --user 0 com.bbk.account
#adb shell pm uninstall --user 0 com.bbk.SuperPowerSave
adb shell pm uninstall --user 0 com.iqoo.engineermode
#adb shell pm uninstall --user 0 com.iqoo.powersaving
adb shell pm uninstall --user 0 com.vivo.abe
adb shell pm uninstall --user 0 com.vivo.agent
adb shell pm uninstall --user 0 com.vivo.audiofx
adb shell pm uninstall --user 0 com.vivo.bsptest
adb shell pm uninstall --user 0 com.vivo.daemonService
adb shell pm uninstall --user 0 com.vivo.floatingball
adb shell pm uninstall --user 0 com.vivo.fuelsummary
adb shell pm uninstall --user 0 com.vivo.hiboard
adb shell pm uninstall --user 0 com.vivo.hybrid
adb shell pm uninstall --user 0 com.vivo.magazine
adb shell pm uninstall --user 0 com.vivo.minscreen
adb shell pm uninstall --user 0 com.vivo.motionrecognition
adb shell pm uninstall --user 0 com.vivo.networkimprove
adb shell pm uninstall --user 0 com.vivo.networkstate
adb shell pm uninstall --user 0 com.vivo.nightpearl
adb shell pm uninstall --user 0 com.vivo.numbermark
adb shell pm uninstall --user 0 com.vivo.pem
#adb shell pm uninstall --user 0 com.vivo.permissionmanager
adb shell pm uninstall --user 0 com.vivo.pushservice
adb shell pm uninstall --user 0 com.vivo.quickpay
adb shell pm uninstall --user 0 com.vivo.safecenter
adb shell pm uninstall --user 0 com.vivo.sdkplugin
adb shell pm uninstall --user 0 com.vivo.secime.service
adb shell pm uninstall --user 0 com.vivo.sim.contacts
adb shell pm uninstall --user 0 com.vivo.upnpserver
adb shell pm uninstall --user 0 com.vivo.wallet
adb shell pm uninstall --user 0 com.vivo.epm
adb shell pm uninstall --user 0 com.vivo.sos
adb shell pm uninstall --user 0 com.vivo.singularity
adb shell pm uninstall --user 0 com.android.vivo.tws.vivotws
adb shell pm uninstall --user 0 com.ringclip
adb shell pm uninstall --user 0 com.dsi.ant.server
adb shell pm uninstall --user 0 com.qualcomm.qti.qmmi
adb shell pm uninstall --user 0 com.android.providers.downloads.ui
adb shell pm uninstall --user 0 com.qualcomm.qti.uceShimService
adb shell pm uninstall --user 0 com.android.printspooler
adb shell pm uninstall --user 0 com.google.android.printservice.recommendation
#adb shell pm uninstall --user 0 com.android.htmlviewer
#adb shell pm uninstall --user 0 com.android.filemanager
adb shell pm uninstall --user 0 com.vivo.share
adb shell pm uninstall --user 0 com.vivo.smartanswer
adb shell pm uninstall --user 0 com.vivo.vms
adb shell pm uninstall --user 0 com.vivo.widget.cleanspeed
adb shell pm uninstall --user 0 com.vivo.vhomeguide
adb shell pm uninstall --user 0 com.vivo.deformer
adb shell pm uninstall --user 0 com.android.documentsui
adb shell pm uninstall --user 0 com.vivo.iotserver
PAUSE